spring:
   datasource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5433/postgres
      username: postgres
      password: pass
   jpa:
      properties.hibernate:
         show_sql: true
         format_sql: true
         hbm2ddl.auto: validate
      open-in-view: false
   mvc:
     format:
        date: iso

   security:
     oauth2:
       client:
          registration:
            google:
               client-id: 886982415727-tvhlqfa23nbr2igj81vctpjqajetu8ke.apps.googleusercontent.com
               client-secret: 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
               redirect-uri: http://localhost:8080/login/oauth2/code/google
               scope: openid,email,profile
               authorization-grant-type: authorization_code
               client-name: Google
               client-authentication-method: client_secret_post

#springdoc:
#   swagger-ui:
#      oauth:
#         client-id: 886982415727-tvhlqfa23nbr2igj81vctpjqajetu8ke.apps.googleusercontent.com
#         client-secret: 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
#         scopes: openid,email,profile
#      oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html
#     path: /swagger-ui.html

back-blaze:
   b2:
      applicationKeyId: 005c77128b8938e0000000001
      applicationKey: K005rzLGMOBbGqTiEN/0vkdPz/V6SO0
      bucketName: personal-project-images
      userAgent: personal-project


logging:
   level:
      org:
         springframework:
            security: trace





